version: '2'

services:
  redis:
    image: redis:3.0.3
    container_name: redis
    volumes:
      - ./docker/data/redis:/data
    ports:
      - "6379:6379"

  mongo:
    image: mongo:3.6.6
    container_name: mongodb
    volumes:
      - ./docker/data/mongo:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.7.4-management
    container_name: rabbitmq
    volumes:
      # Warning: This volume mapping is not officially documented
      - ./docker/data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq

  app:
    build: .
    container_name: generic-template
    command: npm start
    depends_on:
     - rabbitmq
     - redis
     - mongo
    environment:
     - REDIS_URL=redis://redis:6379
     - MONGODB_URL=mongodb://mongo/generic-template
     - RABBITMQ_URI=amqp://guest:guest@rabbitmq
